units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # padding to the right of keys for microcontroller
  pmc: 2.4px
  # microcontroller dimensions
  mx: 18
  my: 33
  # microcontroller y offset
  moy: -5.8
  $default_width: cx
  $default_height: cy

points:
  zones:
    # The primary 6x4 key matrix, plus 3 modifiers.
    matrix:
      anchor:
        shift: [150, -180]
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
        tags: [switch]

      columns:
        # Hide the first two mods and the last mod.
        # Provide a Sofle-like column stagger.
        outer:
          rows.mod.skip: true
          key.column_net: P19
        pinky:
          rows.mod.skip: true
          key.column_net: P18

        ring:
          key.stagger: 5
          key.column_net: P15

          rows.mod.column_net: P19

        middle:
          key.stagger: 2.5
          key.column_net: P14
          rows.mod.column_net: P18
        index:
          key.stagger: -2.5
          key.column_net: P16
          rows.mod.column_net: P15

        inner:
          rows.mod.skip: true
          key.stagger: -2.5
          key.column_net: P10
      rows:
        # Four main rows, one partial row.
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
        num:
          row_net: P5
    # Thumb cluster for Layer and Space keys.
    thumbs:
      # Choc spacing
      key:
        padding: 1ky

        spread: 1kx
        tags: [switch]

      # Place thumbs where the inner mod would go.
      anchor:
        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        # Fan thumbs out by -15 degrees.
        layer:
          key:
            splay: -15
            column_net: P14
        # Spacebar uses a 1.5 wide key.
        space:
          key:
            width: 1.5kx
            splay: 75
            shift: [0, -2]
            column_net: P16
      rows:
        # Thumbs only have one row.
        cluster:
          row_net: P9
    mcu:
      anchor:
        ref.aggregate.parts:
          - ref: matrix_inner_num
          - - ref: matrix_inner_num

            - ref: matrix_index_num
              shift: [pmc+0.5px, 0]
              affect: "x"
    oled_cover_mount_left:
      key.tags: [oled_cover_mount]

      anchor:
        - ref: mcu
        - ref: matrix_inner_bottom
          affect: "y"
          shift: [0, 6.8]
        - shift: [-8, 0]
    oled_cover_mount_right:
      key.tags: [oled_cover_mount]
      anchor:
        - ref: mcu
        - ref: matrix_inner_bottom
          affect: "y"
          shift: [0, 6.8]
        - shift: [8, 0]
    mount_top_left:
      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:
            - ref: matrix_outer_num
            - ref: matrix_pinky_num
            - ref: matrix_pinky_top
            - ref: matrix_outer_top
    mount_top_right:
      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:
            - ref: matrix_inner_num
            - ref: matrix_index_num

            - ref: matrix_index_top
            - ref: matrix_inner_top
        - shift: [-0.3, 1.25]
    mount_bottom_left:
      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:
            - ref: matrix_outer_home
            - ref: matrix_pinky_home
            - ref: matrix_pinky_bottom
            - ref: matrix_outer_bottom
    mount_bottom_right:
      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:
            - ref: matrix_inner_home

            - ref: matrix_index_home

            - ref: matrix_index_bottom
            - ref: matrix_inner_bottom
        - shift: [-0.3, 1.25]
    mount_thumb:
      key.tags: [mount]
      anchor:
        - ref: thumbs_layer_cluster
        - shift: [0.5kx+1.5, 0.5ky-0.5]
    encoder:
      anchor:
        - ref: mcu
        - ref: matrix_inner_bottom
          affect: "y"
        - shift: [0, -5.3]

outlines:
  _keys_1u:
    - what: rectangle

      where: [[switch, -thumbs_space_cluster]]
      size: [kx-0.5, ky-0.5]
  _key_thumb:
    - what: rectangle
      where: thumbs_space_cluster
      size: [1.5kx-0.5, 1ky-0.5]
  keys:
    - "_keys_1u"
    - "_key_thumb"

  _micro:
    - what: rectangle
      where:
        ref: mcu
        # rotate: -90
      adjust:
        shift: [0, -10]
      size: [mx, my]
  _plate_keys:
    - what: rectangle
      where: [switch]
      size: 14
  _plate_mounts:
    - what: circle
      where: [mount]
      radius: 1.1
  _right_side:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_index_num
          shift: [0.5px, 0.5ky]
        - ref: matrix_index_num

          shift: [pmc, 0.5ky]

        - shift: [0, -4.2ky]

        - ref: thumbs_space_cluster
          shift: [0.65px, -0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.75px, -0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.75px, 0.5py]

        - ref: matrix_index_mod
          shift: [2, -0.5py]
  _left_side:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num

          shift: [-0.75px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.75px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: matrix_index_mod
          shift: [0.2px, -0.5py]
        - ref: matrix_ring_mod

          shift: [-0.3px, -0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]

  _plate_mcu_cutout:
    - what: polygon
      operation: stack
      points:
        - - ref: mcu
          - ref: matrix_inner_bottom
            affect: "y"
            shift: [0, 6.6]
          - shift: [-12, -2]
        - shift: [40, 0]
        - shift: [0, 80]
        - shift: [-40, 0]

  _encoder_cutout:
    - what: rectangle
      where:
        ref: encoder
      size: [12, 12]
    - operation: add
      what: rectangle
      where:
        ref: encoder
      size: [12, 2.5]
      adjust.shift: [0, 6]

  outline:
    - "_left_side"
    - operation: add
      name: "_right_side"
      fillet: 2
  combo:
    - "outline"
    - "-keys"
    # - "-_micro"
  plate:
    - "outline"
    - "-_plate_keys"
    - "-_plate_mcu_cutout"
    - operation: subtract
      name: "_encoder_cutout"
      fillet: 0.8
    - "-_plate_mounts"

  oled_cover:
    - "outline"
    - operation: intersect
      name: "_plate_mcu_cutout"
      fillet: 0.8
    - operation: subtract
      what: circle
      where: [oled_cover_mount]
      radius: 1.1

pcbs:
  main:
    template: kicad8
    outlines.main:
      outline: outline
    footprints:
      switch:
        what: ceoloide/switch_choc_v1_v2
        where: [switch]
        params:
          reversible: true
          choc_v2_support: false
          include_corner_marks: true
          # built in traces and vias violate jlcpcb capabilities
          include_traces_vias: false
          from: "{{column_net}}"
          to: "{{colrow}}"
          switch_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Choc_V1_Switch.step"
          switch_3dmodel_xyz_rotation: [0, 180, 180]
          switch_3dmodel_xyz_offset: [0, 0, -1.6]
          keycap_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Choc_V1_Keycap_MBK_Black_1u.step"
          keycap_3dmodel_xyz_rotation: [0, 180, 0]
          keycap_3dmodel_xyz_offset: [0, 0, -8.2]
          hotswap_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Choc_V1_Hotswap.step"
          hotswap_3dmodel_xyz_rotation: [0, 180, 180]
          hotswap_3dmodel_xyz_offset: [0, 0, -1.6]

      diode:
        what: ceoloide/diode_tht_sod123
        where: [switch]
        adjust:
          shift: [8, -3]
          rotate: 90
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
          diode_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Diode_1N4148W.step"
          diode_3dmodel_xyz_rotation: [-90, 180, 180]
          diode_3dmodel_xyz_offset: [0, 0, -2.3]

      mcu:
        what: ceoloide/mcu_nice_nano
        params:
          reversible: true
          reverse_mount: true
          only_required_jumpers: true
          mcu_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Nice_Nano_V2.step"
          mcu_3dmodel_xyz_offset: [0, 0, 5.0]
          P21: MOSI
          P20: SCK
          P1: CS
          P21_label: "P21"
          P20_label: "P20"
          P1_label: "P1"
        where:
          ref: mcu
          shift: [0, moy]

      display:
        what: ceoloide/display_nice_view
        params:
          reversible: true
          invert_jumpers_position: true
          # MOSI: P21
          # SCK: P20
          # CS: P1
          niceview_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Nice_View.step"
          pin_header_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/PinHeader_2.54mm_1x-5.step"
          pin_socket_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/PinSocket_2.54mm_5mm_1x-5.step"
          niceview_3dmodel_xyz_offset: [-7, -18, 6.8]
          pin_header_3dmodel_xyz_rotation: [0, 0, -90]
          pin_header_3dmodel_xyz_offset: [0, -16.7, 3]
          pin_socket_3dmodel_xyz_rotation: [-90, 0, 0]
          pin_socket_3dmodel_xyz_offset: [-5.1, -16.7, 0]
        where:
          ref: mcu
          shift: [0, moy-1.9]

      power_switch:
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
          include_silkscreen: false
          from: "RAW"
          to: "BAT_P"
          switch_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Switch_Power.step"
          switch_3dmodel_xyz_rotation: [-90, 0, -90]
        where:
          # edge of board
          ref:
            ref: matrix_index_home
            shift: [pmc, 0]
          shift: [-2.1, 4.25]
      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          reversible: true
          reset_switch_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Switch_Reset.step"
          reset_switch_3dmodel_xyz_rotation: [-90, 0, 0]
        where:
          ref:
            ref: matrix_index_home
            shift: [pmc, 0]
          shift: [-2.2, moy]
          rotate: -90
      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        params:
          include_momentary_switch_pads: false
          include_plate_hole_marking: true
          encoder_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/Encoder_EC12E.step"
          A: P2
          C: P3
        where:
          ref: encoder
        adjust:
          rotate: 180
      navswitch:
        what: sqku_5way_nav_switch
        params:
          # The nav switch goes on the right half only
          side: "B"
          # the common pin is routed to P4, which will act as another column
          # the other pins are rows
          A: P9
          B: P8
          C: P7
          CTR: nav_diode
          D: P5
          CMN: P4
        where:
          ref: encoder
          rotate: -90
      navswitch_diode:
        # For simplicity only the center line has a diode, as it's
        # physically impossible to press two directions on the switch
        # at the same time. Saves space and routing effort.
        what: ceoloide/diode_tht_sod123
        params:
          side: "F"
          from: "nav_diode"
          to: "P6"
          diode_3dmodel_filename: "${KICAD_USER_3DMODEL_DIR}/infused-kim/Diode_1N4148W.step"
          diode_3dmodel_xyz_rotation: [-90, 0, 0]
          diode_3dmodel_xyz_offset: [0, 0, 0.7]
        where:
          ref: encoder
          shift: [-10, 4]
          rotate: -90
      oled_cover_mounts:
        what: ceoloide/mounting_hole_plated
        where: [oled_cover_mount]
      jst:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          reversible: true
        where:
          ref: oled_cover_mount_left
          rotate: 90
          shift: [0, 5.8]
      mounts:
        what: ceoloide/mounting_hole_npth
        where: [mount]
        params:
          hole_size: 4.1
          hole_drill: 4.1
      gndplane:
        what: ceoloide/utility_filled_zone
        params:
          remove_islands: "below_area_limit"
          min_island_size: 100
          side: "F&B"
      nice_view_jumper_routes:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.display.where
        params:
          locked: false
          routes:
            - "F(2.49,19.3)(2.54,19.35)(-0.85,19.35)(-0.9,19.3)V"  # net: SCK
            - "B(-0.95,19.35)(-2.54,19.35)"  # net: SCK
            - "B(-0.9,19.3)(-0.95,19.35)"  # net: SCK
            - "F(-1.15,23.8)(-2.54,22.41)(-2.54,20.3)(-2.54,20.175)V(1.715,20.175)(2.54,19.35)"  # net: GND
            - "F(-2.54,20.3)(-2.54,19.35)"  # net: GND
            - "F(5.08,19.35)(4.55,19.35)(3.9,2E+1)V(3.099,20.801)(-3.629,20.801)(-5.08,19.35)"  # net: MOSI
            - "(-4.15,21.3)VB(3.68,21.3)(5.08,19.9)(5.08,19.35)"  # net: CS
            - "F(-5.08,19.35)(-5.08,20.37)(-4.15,21.3)"  # net: CS
      mcu_routes_power:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.mcu.where
        params:
          locked: false
          routes:
            - "F(3.4,-12.7)(3.4,-14.25)(3.95,-14.8)"  # net: RAW
            - "B(0,18.6)(-2.7,15.9)(-2.7,-3.3)(-1.15,-4.85)"  # net: VCC
            - "(4.1,-14.8)VB(8.85,-14.8)(9.35,-14.3)(9.35,15.37)(7.36,17.36)(7.36,17.7)"  # net: RAW
      mcu_routes_niceview:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.mcu.where
        params:
          locked: false
          routes:
            - "B(7.62,0)(4.2,0)(2.5,1.7)(2.5,15.9)V(1.3,17.1)(1.3,19)(-0.9,21.2)"  # net: SCK
            - "B(7.62,-2.54)(4.14,-2.54)(1.5,0.1)(1.5,12.9)V(3.9,15.3)(3.9,21.9)"  # net: MOSI
            - "F(-4.15,23.2)(-3.8,22.85)(-3.8,-1)(-1.3,-3.5)(-1.3,-10.6)(-3.4,-12.7)"  # net: CS
      mcu_routes_cols:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.mcu.where
        params:
          locked: false
          width: 0.2
          routes:
            - "F(-19.625,-11.75)(-16.775,-14.6)(-0.09159,-14.6)(0.4,-14.10841)(0.4,9.9)(5,14.5)V(5.74,15.24)(7.62,15.24)"  # net: P10
            - "F(-55.625,-16.75)(-52.503,-19.872)(-42.25046,-19.872)(-16.19165,-15.60006)(-15.90759,-15.316)(0.12014,-15.316)(1.172,-14.26414)(1.172,5.872)(5,9.7)V(5.46,10.16)(7.62,10.16)"  # net: P14
            - "F(-37.625,-14.25)(-35.175,-16.7)(-24.92876,-16.7)(-16.34892,-15.29347)(-16.04345,-14.988)(-0.01572,-14.988)(0.8,-14.17228)(0.8,7.8)(5,12)V(5.7,12.7)(7.62,12.7)"  # net: P16
            - "B(7.62,7.62)(5.82,7.62)(5.1,6.9)V(1.5,3.3)(1.5,-14.4)(0.256,-15.644)(-15.77172,-15.644)(-16.03438,-15.90666)(-42.22376,-20.2)(-67.675,-20.2)(-73.625,-14.25)"  # net: P15
            - "B(7.62,5.08)(5.48,5.08)(5.1,4.7)V(1.919,1.519)(1.919,-14.481)(0.428,-15.972)(-15.63586,-15.972)(-15.87712,-16.21326)(-42.26728,-20.53951)(-42.6541,-20.571)(-75.15299,-20.571)(-75.53263,-20.54182)(-81.21132,-19.66368)(-91.625,-9.25)"  # net: P18
            - "B(7.62,2.54)(5.64,2.54)(5.1,2)V(2.247,-0.853)(2.247,-14.653)(0.6,-16.3)(-15.5,-16.3)(-15.71985,-16.51985)(-42.22739,-20.86535)(-42.64076,-20.899)(-75.16559,-20.899)(-75.57031,-20.8679)(-102.1114,-16.7636)(-109.625,-9.25)"  # net: P19
      jst_routes_power:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.jst.where
        params:
          locked: false
          routes:
            - "B(1,2.475)(1,8.7)(7.16,14.86)(7.16,15.46)"  # net: BAT_P
            - "F(-1,2.475)(-1,4.2)(-0.6,4.6)V(1,6.2)"  # net: BAT_P
      power_switch_routes:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.power_switch.where
        params:
          locked: false
          routes:
            - "B(-1.94,0.75)(-2.94,1.75)(-2.94,3.31)(-2.3,3.95)V(-2.94,3.31)(-2.94,1)(-1.735,-0.205)(-1.735,-0.75)"  # net: BAT_P
            - "B(-1.735,-2.25)(-2.44,-2.955)(-2.44,-3.75)V(-2.44,-2.955)(-1.735,-2.25)"  # net: RAW
      reset_switch_routes:
        what: ceoloide/utility_router
        where:
          $extends: pcbs.main.footprints.reset.where
        params:
          locked: false
          routes:
            - "F(-39.12,6.3)(-38.32,7.1)(-36.09432,7.1)(-32.43532,3.441)(-6.141,3.441)(-4.55,1.85)V(-3.55,0.85)(-2.625,0.85)"  # net: RST
            - "F(-4.55,1.85)(-3.55,0.85)(-2.625,0.85)"  # net: RST
      switch_route_rev_colpads:
        what: ceoloide/utility_router
        where: [switch]
        params:
          locked: false
          net: "{{column_net}}"
          routes:
            - "B(-3.275,-5.95)(-1.025,-8.2)(-0.1,-8.2)V(1.025,-8.2)(3.275,-5.95)" 
      switch_route_rev_colrowpads:
        what: ceoloide/utility_router
        where: [switch]
        params:
          net: "{{colrow}}"
          locked: false
          routes:
            - "B(8.275,-3.75)(6.125,-1.6)(2.81332,-1.6)(2.21332,-2.2)(-2.4531,-2.2)(-3.0531,-1.6)(-5.6,-1.6)V(-6.125,-1.6)(-8.275,-3.75)"
            - "B(6.125,-1.6)(7.1,-1.6)(8,-0.7)"
      switch_route_cols:
        what: ceoloide/utility_router
        where: [[/^matrix_.*/, -/^matrix_.*_(bottom|mod)/]]
        params:
          locked: false
          net: "{{column_net}}"
          routes:
            - "F(3,-5.675)(3,10.775)"
      switch_route_rows_outer_pinky:
        what: ceoloide/utility_router
        where: [/^matrix_outer_.*/]
        adjust:
          $extends: pcbs.main.footprints.diode.adjust
        params:
          locked: false
          net: "{{row_net}}"
          routes:
            - "(-1.5,2.75)VB(-1.5,17.85)"
            - "B(-1.65,0)(-1.65,2.6)F(-1.65,0)"
      switch_route_rows_pinky_ring:
        what: ceoloide/utility_router
        where: [/^matrix_pinky_.*/]
        adjust:
          $extends: pcbs.main.footprints.diode.adjust
        params:
          locked: false
          net: "{{row_net}}"
          routes:
            - "B(3.35,18)(3.35,5.85)(-0.75,1.75)V(-1.65,0.85)(-1.65,0)"
            - "B(-0.75,1.75)(-1.65,0.85)(-1.65,0)"
      switch_route_rows_ring_middle:
        what: ceoloide/utility_router
        where: /^matrix_ring_.*/ 
        adjust:
          $extends: pcbs.main.footprints.diode.adjust
        params:
          locked: false
          net: "{{row_net}}"
          routes:
            - "B(0.85,18)(0.85,4.85)(-0.75,3.25)V(-1.65,2.35)(-1.65,0)"
            - "B(-0.75,3.25)(-1.65,2.35)(-1.65,0)"
      switch_route_rows_middle_index:
        what: ceoloide/utility_router
        where: /^matrix_middle_.*/
        adjust:
          $extends: pcbs.main.footprints.diode.adjust
        params:
          locked: false
          net: "{{row_net}}"
          routes:
            - "B(-4.15,18)(-4.15,4.4)(-2.25,2.5)V(-1.65,1.9)(-1.65,0)"
            - "B(-2.25,2.5)(-1.65,1.9)(-1.65,0)"
      switch_route_rows_index_inner:
        what: ceoloide/utility_router
        where: [[/^matrix_index_.*/, -matrix_index_mod]]
        adjust:
          $extends: pcbs.main.footprints.diode.adjust
        params:
          locked: false
          net: "{{row_net}}"
          routes:
            - "B(-4.15,18)(-4.15,4.65)(-2.25,2.75)V(-1.65,2.15)(-1.65,0)"
            - "B(-2.25,2.75)(-1.65,2.15)(-1.65,0)"
      diode_route_colrow_pads:
        what: ceoloide/utility_router
        where: [switch]
        adjust:
          $extends: pcbs.main.footprints.diode.adjust
        params:
          net: "{{colrow}}"
          locked: false
          routes:
            - "(4.6,-0.9)VB(3.7,-0)(1.65,-0)F(3.7,-0)(4.6,-0.9)"

 
  top_plate:
    outlines.main:
      outline: plate
    template: kicad8
    footprints:
      mounts:
        what: ceoloide/mounting_hole_plated
        where: [mount]
