units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # padding to the right of keys for microcontroller
  pmc: 2.4px
  # microcontroller dimensions
  mx: 18
  my: 33
  # microcontroller y offset
  moy: -5.8
  $default_width: cx
  $default_height: cy

points:
  zones:
    # The primary 6x4 key matrix, plus 3 modifiers.
    matrix:
      anchor:
        shift: [150, -180]
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
        tags: [switch]

      columns:
        # Hide the first two mods and the last mod.
        # Provide a Sofle-like column stagger.
        outer:
          rows.mod.skip: true
          key.column_net: P19
        pinky:
          rows.mod.skip: true
          key.column_net: P18

        ring:
          key.stagger: 5
          key.column_net: P15

          rows.mod.column_net: P19

        middle:
          key.stagger: 2.5
          key.column_net: P14
          rows.mod.column_net: P18
        index:
          key.stagger: -2.5
          key.column_net: P16
          rows.mod.column_net: P15

        inner:
          rows.mod.skip: true
          key.stagger: -2.5
          key.column_net: P10
      rows:
        # Four main rows, one partial row.
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7

        top:

          row_net: P6
        num:
          row_net: P5
    # Thumb cluster for Layer and Space keys.
    thumbs:
      # Choc spacing
      key:

        padding: 1ky

        spread: 1kx
        tags: [switch]

      # Place thumbs where the inner mod would go.
      anchor:

        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        # Fan thumbs out by -15 degrees.
        layer:
          key:
            splay: -15
            column_net: P14
        # Spacebar uses a 1.5 wide key.
        space:

          key:
            width: 1.5kx
            splay: 75
            shift: [0,-2]
            column_net: P16
      rows:
        # Thumbs only have one row.
        cluster:

          row_net: P9
    mcu:
      anchor:

        ref.aggregate.parts:

          - ref: matrix_inner_num
          - - ref: matrix_inner_num

            - ref: matrix_index_num
              shift: [pmc+0.5px,0]
              affect: "x"
    oled_cover_mount_left:

      key.tags: [oled_cover_mount]

      anchor:
        - ref: mcu
        - ref: matrix_inner_bottom
          affect: "y"
          shift: [0, 6.8]
        - shift: [-8, 0]
    oled_cover_mount_right:
      key.tags: [oled_cover_mount]
      anchor:
        - ref: mcu
        - ref: matrix_inner_bottom
          affect: "y"
          shift: [0, 6.8]
        - shift: [8, 0]
    mount_top_left:

      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:
          - ref: matrix_outer_num
          - ref: matrix_pinky_num
          - ref: matrix_pinky_top
          - ref: matrix_outer_top
    mount_top_right:
      key.tags: [mount]
      anchor:

        - ref.aggregate.parts:
          - ref: matrix_inner_num
          - ref: matrix_index_num

          - ref: matrix_index_top
          - ref: matrix_inner_top
        - shift: [-0.3, 1.25]
    mount_bottom_left:
      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:
          - ref: matrix_outer_home
          - ref: matrix_pinky_home
          - ref: matrix_pinky_bottom
          - ref: matrix_outer_bottom
    mount_bottom_right:
      key.tags: [mount]
      anchor:
        - ref.aggregate.parts:

          - ref: matrix_inner_home

          - ref: matrix_index_home

          - ref: matrix_index_bottom
          - ref: matrix_inner_bottom
        - shift: [-0.3, 1.25]
    mount_thumb:
      key.tags: [mount]
      anchor:
        - ref: thumbs_layer_cluster
        - shift: [0.5kx+1.5, 0.5ky-0.5]
    encoder:
      anchor:
        - ref: mcu
        - ref: matrix_inner_bottom
          affect: "y"
        - shift: [0, -5.3]


outlines:
  _keys_1u:
    - what: rectangle

      where: [[switch, -thumbs_space_cluster]]
      size: [kx-0.5,ky-0.5]
  _key_thumb:
    - what: rectangle
      where: thumbs_space_cluster
      size: [1.5kx-0.5, 1ky-0.5]
  keys:
    - "_keys_1u"
    - "_key_thumb"


  _micro:
    - what: rectangle
      where:
          ref: mcu
          # rotate: -90
      adjust:
        shift: [0, -10]
      size: [mx, my]
  _plate_keys:
    - what: rectangle
      where: [switch]
      size: 14
  _plate_mounts:
    - what: circle
      where: [mount]
      radius: 1.1
  _right_side:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_index_num
          shift: [0.5px,0.5ky]
        - ref: matrix_index_num

          shift: [pmc,0.5ky]

        - shift: [0, -4.2ky]

        - ref: thumbs_space_cluster
          shift: [0.65px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.75px,0.5py]

        - ref: matrix_index_mod
          shift: [2, -0.5py]
  _left_side:

    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_num

          shift: [-0.75px,0.5py]
        - ref: matrix_middle_num
          shift: [0.75px,0.5py]
        - ref: matrix_inner_num
          shift: [0.5px,0.5py]
        - ref: matrix_index_mod
          shift: [0.2px,-0.5py]
        - ref: matrix_ring_mod

          shift: [-0.3px,-0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]

  _plate_mcu_cutout:
    - what: polygon
      operation: stack
      points:
        - - ref: mcu
          - ref: matrix_inner_bottom
            affect: "y"
            shift: [0, 6.6]
          - shift: [-12, -2]
        - shift: [40, 0]
        - shift: [0, 80]
        - shift: [-40, 0]

  _encoder_cutout:

    - what: rectangle
      where:
        ref: encoder
      size: [12, 12]
    - operation: add
      what: rectangle
      where:
        ref: encoder
      size: [12, 2.5]
      adjust.shift: [0, 6]



  outline:

    - "_left_side"
    - operation: add
      name: "_right_side"
      fillet: 2
  combo:
    - "outline"
    - "-keys"
    # - "-_micro"
  plate:
    - "outline"
    - "-_plate_keys"
    - "-_plate_mcu_cutout"
    - operation: subtract
      name: "_encoder_cutout"
      fillet: 0.8
    - "-_plate_mounts"

  oled_cover:
    - "outline"
    - operation: intersect
      name: "_plate_mcu_cutout"
      fillet: 0.8
    - operation: subtract
      what: circle
      where: [oled_cover_mount]
      radius: 1.1
    
      
pcbs:
  main:
    template: kicad8
    outlines.main:
      outline: outline
    footprints:
      switch:
        what: ceoloide/switch_choc_v1_v2
        where: [switch]
        params:
          reversible: true
          choc_v2_support: false
          include_corner_marks: true
          from: "{{column_net}}"
          to: "{{colrow}}"


      diode:
        what: ceoloide/diode_tht_sod123
        where: [switch]
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8, -2.4]
          rotate: 90

      controller:
        what: ceoloide/mcu_nice_nano
        params:
          reversible: true
          reverse_mount: true
          only_required_jumpers: true
        where:
          ref: mcu
          shift: [0, moy]
          # rotate: -90
    
      display:
        what: ceoloide/display_nice_view
        params:
          reversible: true
          MOSI: P21
          SCK: P20
          CS: P1
        where:
          ref: mcu
          shift: [0, moy-2.8]

      power_switch:
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
          include_silkscreen: false
          from: "RAW"
          to: "BAT_P"
        where:
          # edge of board
          ref:
            ref: matrix_index_home
            shift: [pmc,0]
          shift: [-1.86, 4.25]
      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          reversible: true
        where:
          ref:
            ref: matrix_index_home
            shift: [pmc,0]
          shift:
            [-2.2,moy]
          rotate: -90
      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        params:
          include_momentary_switch_pads: false
          include_plate_hole_marking: true
        where:
          ref: encoder
        adjust:
          rotate: 180
      navswitch:
        what: sqku_5way_nav_switch
        params:
          # The nav switch goes on the right half only
          side: 'B'
          # the common pin is routed to P4, which will act as another column
          # the other pins are rows
          A: P9
          B: P8
          C: P7
          CTR: nav_diode
          D: P5
          CMN: P4
        where:
          ref: encoder
          rotate: -90
      navswitch_diode:
        # For simplicity only the center line has a diode, as it's
        # physically impossible to press two directions on the switch
        # at the same time. Saves space and routing effort.
        what: ceoloide/diode_tht_sod123
        params:
          side: 'F'
          from: "nav_diode"
          to: "P6"
        where:
          ref: encoder
          shift: [-10, 4]
          rotate: -90
      oled_cover_mounts:
        what: ceoloide/mounting_hole_plated
        where: [oled_cover_mount]
      jst:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          reversible: true
        where:
          ref: oled_cover_mount_left
          rotate: 90
          shift: [0, 5.8]
      mounts:
        what: ceoloide/mounting_hole_npth
        where: [mount]
        params:
          hole_size: 4.1
          hole_drill: 4.1
      gndplane:
        what: ceoloide/utility_filled_zone
        params:
          remove_islands: 'below_area_limit'
          side: "F&B"
  top_plate:
    outlines.main:
      outline: plate
    template: kicad8
    footprints:
      mounts:
        what: ceoloide/mounting_hole_plated
        where: [mount]
      
