units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables

  px: kx + 4
  py: ky + 4
  # padding to the right of keys for microcontroller
  pmc: 2.4px
  # microcontroller dimensions
  mx: 18
  my: 33
  # microcontroller y offset
  moy: -10
  $default_width: cx
  $default_height: cy

points:
  zones:
    # The primary 6x4 key matrix, plus 3 modifiers.
    matrix:
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
        tags: [switch]

      columns:
        # Hide the first two mods and the last mod.
        # Provide a Sofle-like column stagger.
        outer:
          rows.mod.skip: true
        pinky:
          rows.mod.skip: true
        ring:
          key.stagger: 5
        middle:
          key.stagger: 2.5
        index:
          key.stagger: -2.5
        inner:
          rows.mod.skip: true
          key.stagger: -2.5
      rows:
        # Four main rows, one partial row.
        mod:
        bottom:
        home:
        top:
        num:
    # Thumb cluster for Layer and Space keys.
    thumbs:
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
        tags: [switch]

      # Place thumbs where the inner mod would go.
      anchor:

        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        # Fan thumbs out by -15 degrees.
        layer:
          key:
            splay: -15
        # Spacebar uses a 1.5 wide key.
        space:
          key:
            width: 1.5kx
            splay: 75
            shift: [0,-2]
      rows:
        # Thumbs only have one row.
        cluster:
    mcu:
      anchor:
        ref.aggregate.parts:
          - ref: matrix_inner_num
          - - ref: matrix_inner_num
            - ref: matrix_index_num
              shift: [pmc+0.5kx,0]
              affect: "x"

outlines:
  _keys_1u:
    - what: rectangle
      where: [[switch, -thumbs_space_cluster]]
      size: [kx-0.5,ky-0.5]
  _key_thumb:
    - what: rectangle
      where: thumbs_space_cluster
      size: [1.5kx-0.5, 1ky-0.5]
  keys:
    - "_keys_1u"
    - "_key_thumb"

  _micro:
    - what: rectangle
      where:
          ref: mcu
          # rotate: -90
      adjust:
        shift: [0, -10]
      size: [mx, my]
  plate_keys:
    - what: rectangle
      where: [switch]
      size: 14
  right_side:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_index_num
          shift: [0.5px,0.5ky]
        - ref: matrix_index_num
          shift: [pmc,0.5ky]
        - shift: [0, -4.2ky]
        - ref: thumbs_space_cluster
          shift: [0.65px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.75px,0.5py]
        - ref: matrix_index_mod
          shift: [2, -0.5py]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_num
          shift: [-0.75px,0.5py]
        - ref: matrix_middle_num
          shift: [0.75px,0.5py]
        - ref: matrix_inner_num
          shift: [0.5px,0.5py]
        - ref: matrix_index_mod
          shift: [0.2px,-0.5py]
        - ref: matrix_ring_mod
          shift: [-0.3px,-0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
  outline:
    - "board"
    - operation: add
      name: "right_side"
      fillet: 2
  combo:
    - "outline"
    - "-keys"
    # - "-_micro"
  plate:
    - "outline"
    - "-plate_keys"

pcbs.main:
  template: kicad8
  outlines.main:
    outline: outline
  footprints:
    switch:
      what: choc
      where: [switch]
      params:
        keycaps: true
        reverse: true
        hotswap: true
        from: "{{column_net}}"
        to: "{{colrow}}"

    diode:
      what: ceoloide/diode_tht_sod123
      where: true
      params:
        reversible: true
        from: "{{colrow}}"
        to: "{{row_net}}"
      adjust:
        shift: [0, -5]

    controller:
      what: ceoloide/mcu_nice_nano
      params:
        reversible: true
        reverse_mount: true
        only_required_jumpers: true
      where:
        ref: mcu
        shift: [0, moy]
        # rotate: -90
  
    display:
      what: ceoloide/display_nice_view
      params:
        reversible: true
        MOSI: P2
        SCK: P3
        CS: P1
      where:
        ref: mcu
        shift: [0, moy-2.8]
    power_switch:
      what: ceoloide/power_switch_smd_side
      params:
        reversible: true
        include_silkscreen: false
      where:
        # edge of board
        ref:
          ref: matrix_index_home
          shift: [pmc,0]
        shift: [-1.86, -0.25]
    reset:
      what: ceoloide/reset_switch_smd_side
      params:
        reversible: true
      where:
        ref:
          ref: matrix_index_home
          shift: [pmc,0]
        shift:
          [-2.2,-10]
        rotate: -90
        


